[package]
name = "rs-gemini-genai"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.15"
strum = { version = "0.27.1", features = ["derive"] }
serde_json = "1.0.140"
strum_macros = "0.27.1"
